name: CI/CD

on:
    push:
        branches:
            - development # Trigger on pushes to the 'development' branch

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest # Specify the operating system

        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 'v18.17.1' # Set Node.js version to v18.17.1

            - name: Install Dependencies
              run: npm install

            - name: Build the project
              run: npm run build # Ensure this command builds the 'build' folder

            - name: Deploy to GitHub Pages
              uses: actions/checkout@v3 # Checkout gh-pages branch
              with:
                  repository: ${{ github.repository }}
                  ref: gh-pages
                  token: ${{ secrets.GITHUB_TOKEN }} # Use your personal access token

            - name: Copy build folder to gh-pages root
              run: |
                  rm -rf *  # Remove existing files in gh-pages branch (optional)
                  cp -r ./build/* ./  # Copy all files from 'build' to the root
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"
                  git add .
                  git commit -m "Deploy from development branch"
                  git push origin gh-pages --quiet
