name: CI/CD

on:
    push:
        branches:
            - development # Trigger on pushes to the 'development' branch

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x' # Update to your desired Node.js version

            - name: Install Dependencies
              run: npm install

            - name: Build the project
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
                  publish_dir: ./build
                  publish_branch: gh-pages

            - name: Clean up build files
              run: rm -rf build
